import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
        flex: 1,
        backgroundColor: 'white',
      },
  header: {
        width: '100%',
        height: 70,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: 20,
        paddingRight: 20,
        marginTop: 25,
      },
      menuBtn: {
        width: 40,
        height: 40,
      },  
      cartBtn: {
        width: 28,
        height: 28,
      },  
      categorieBox1: {
        width: 265,
        height: 257,
        backgroundColor: '#618FCA',
        borderRadius: 25,
        marginLeft: 17,
        marginBottom: 28,
        shadowColor: 'black',
        shadowOffset: {
          width: 0,
          height: 3,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      football: {
        width: 252,
        height: 120,
        alignSelf: 'center',
        borderRadius: 20,
        marginTop: 5,
      },
      rate: {
        width: 20,
        height: 20,
        marginLeft: 18,
        marginTop: 8,
      },
      categorieBox2: {
        width: 265,
        height: 257,
        backgroundColor: '#618FCA',
        borderRadius: 25,
        marginLeft: 10,
        shadowColor: 'black',
        shadowOffset: {
          width: 0,
          height: 3,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      homeworkout: {
        width: 252,
        height: 120,
        alignSelf: 'center',
        borderRadius: 20,
        marginTop: 5,
      },
      categorieBox3: {
        width: 265,
        height: 260,
        backgroundColor: '#618FCA',
        borderRadius: 25,
        marginLeft: 10,
        shadowColor: 'black',
        shadowOffset: {
          width: 0,
          height: 3,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      community: {
        width: 252,
        height: 120,
        alignSelf: 'center',
        borderRadius: 20,
        marginTop: 5,
      },
      categorieBox4: {
        width: 265,
        height: 260,
        backgroundColor: '#618FCA',
        borderRadius: 25,
        marginLeft: 10,
        marginRight: 17,
        shadowColor: 'black',
        shadowOffset: {
          width: 0,
          height: 3,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
      },
      equipment: {
        width: 252,
        height: 120,
        alignSelf: 'center',
        borderRadius: 20,
        marginTop: 5,
      },
      content1: {
        width: 365,
        height: 145,
        borderWidth: 1,
        alignSelf: 'center',
        borderRadius: 25,
        justifyContent: 'center',
        marginTop: 10,
      },
      contentImage1: {
        width: 365,
        height: 145,
        borderWidth: 1,
        alignSelf: 'center',
        borderRadius: 25,
      },
      moveBtn: {
        width: 35, 
        height: 35, 
        position: 'absolute',
        backgroundColor: 'white', borderRadius: 50, 
        right: 0, 
        bottom: 0,
        marginBottom: 15,
        marginRight: 15,
        justifyContent: 'center',
        alignItems: 'center',
      },
      moveIcon: {
        width: 35,
        height: 35,
      },
      content2: {
        width: 365,
        height: 145,
        borderWidth: 1,
        alignSelf: 'center',
        borderRadius: 25,
        justifyContent: 'center',
        marginTop: 8
      },
      content3: {
        width: 365,
        height: 145,
        borderWidth: 1,
        alignSelf: 'center',
        borderRadius: 25,
        justifyContent: 'center',
        marginTop: 8,
        marginBottom: 15
      },
      
})

export default styles;