import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
    },
    header: {
        width: 345,
        height: 70,
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
        marginLeft: 78,
        marginTop: 35,
    },
    goBack: {
        width: 40,
        height: 40,
        borderRadius: 30,
        backgroundColor: '#434343',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 45,
    },
    backIcon: {
        width: 20,
        height: 20,
    },
    title: {
        fontSize: 30,
        fontFamily: 'Rubik-SemiBold',
        color: 'black',
        textAlign: 'center',
    },
    basicSquat: {
        width: 385,
        height: 290,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 10,
    },
    basicTextContent:{
        width: 190,
        height: 281, 
        position: 'absolute',
        right: 0,
        top: 0,
    },
    basicTitle: {
        fontSize: 23,
        fontFamily: 'Rubik-Medium',
        color: 'black',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        top: 0,
        marginRight: 28,
        marginTop: 40,
    },
    basicDesc: {
        fontSize: 13,
        fontFamily: 'Rubik-Regular',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        marginTop: 110,
        marginLeft: 30,
        marginRight: 18
    },
    line: {
        width: 158,
        height: 1,
        backgroundColor: 'black',
        alignSelf: 'flex-end',
        position: 'absolute',
        bottom: 0,
        right: 0,
        marginRight: 20
    },
    basicSquatGif: {
        width: 210,
        height: 245,
        alignSelf: 'flex=start',
        marginLeft: 5,
        marginTop: 25
    },
    jumpSquat: {
        width: 385,
        height: 290,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 10,
    },
    jumpTextContent:{
        width: 190,
        height: 281, 
        position: 'absolute',
        right: 0,
        top: 0,
    },
    jumpTitle: {
        fontSize: 23,
        fontFamily: 'Rubik-Medium',
        color: 'black',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        top: 0,
        marginRight: 28,
        marginTop: 40,
    },
    jumpDesc: {
        fontSize: 13,
        fontFamily: 'Rubik-Regular',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        marginTop: 110,
        marginLeft: 25,
        marginRight: 18
    },
    line: {
        width: 158,
        height: 1,
        backgroundColor: 'black',
        alignSelf: 'flex-end',
        position: 'absolute',
        bottom: 0,
        right: 0,
        marginRight: 20
    },
    jumpSquatGif: {
        width: 210,
        height: 245,
        alignSelf: 'flex=start',
        marginLeft: 5,
        marginTop: 25
    },
    sumoSquat: {
        width: 385,
        height: 290,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 10,
    },
    sumoTextContent:{
        width: 190,
        height: 281, 
        position: 'absolute',
        right: 0,
        top: 0,
    },
    sumoTitle: {
        fontSize: 23,
        fontFamily: 'Rubik-Medium',
        color: 'black',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        top: 0,
        marginRight: 28,
        marginTop: 40,
    },
    sumoDesc: {
        fontSize: 13,
        fontFamily: 'Rubik-Regular',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        marginTop: 110,
        marginLeft: 25,
        marginRight: 11
    },
    line: {
        width: 158,
        height: 1,
        backgroundColor: 'black',
        alignSelf: 'flex-end',
        position: 'absolute',
        bottom: 0,
        right: 0,
        marginRight: 20
    },
    sumoSquatGif: {
        width: 210,
        height: 245,
        alignSelf: 'flex=start',
        marginLeft: 5,
        marginTop: 25,
    },
    gobletSquat: {
        width: 385,
        height: 290,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 10,
        marginBottom: 50,
    },
    gobletTextContent:{
        width: 190,
        height: 281, 
        position: 'absolute',
        right: 0,
        top: 0,
    },
    gobletTitle: {
        fontSize: 23,
        fontFamily: 'Rubik-Medium',
        color: 'black',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        top: 0,
        marginRight: 18,
        marginTop: 55,
    },
    gobletDesc: {
        fontSize: 13,
        fontFamily: 'Rubik-Regular',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        marginTop: 115,
        marginLeft: 25,
        marginRight: 18
    },
    line: {
        width: 158,
        height: 1,
        backgroundColor: 'black',
        alignSelf: 'flex-end',
        position: 'absolute',
        bottom: 0,
        right: 0,
        marginRight: 20
    },
    gobletSquatGif: {
        width: 210,
        height: 245,
        alignSelf: 'flex=start',
        marginLeft: 5,
        marginTop: 25
    },
})

export default styles;