import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'white',
    },
    header: {
        width: 345,
        height: 70,
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'center',
        marginTop: 32,
    },
    goBack: {
        width: 40,
        height: 40,
        borderRadius: 30,
        backgroundColor: '#434343',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 27,
        marginLeft: 18
    },
    backIcon: {
        width: 20,
        height: 20,
    },
    title: {
        fontSize: 28,
        fontFamily: 'Rubik-SemiBold',
        color: 'black',
        textAlign: 'center',
    },
    skaters: {
        width: 345,
        height: 215,
        justifyContent: 'center',
        alignSelf: 'center',
    },
    skatersTextContent:{
        width: 190,
        height: 265, 
        position: 'absolute',
        right: 0,
        top: 0,
    },
    skatersTitle:{
        fontSize: 26,
        fontFamily: 'Rubik-Medium',
        color: 'black',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        top: 0,
        marginRight: 56,
        marginTop: 30,
    },
    skatersDesc: {
        fontSize: 13,
        fontFamily: 'Rubik-Regular',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        marginTop: 105,
        marginLeft: 28,
        marginRight: 15
    },
    line: {
        width: 155,
        height: 1,
        backgroundColor: 'black',
        alignSelf: 'flex-end',
        position: 'absolute',
        bottom: 0,  
    },
    skatersGif: {
        width: 170,
        height: 220,
        alignSelf: 'flex=start',
        marginLeft: 0,
        marginTop: 30,
    },
    mountainClimber: {
        width: 345,
        height: 215,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 65,
    },
    mountainClimberTextContent:{
        width: 190,
        height: 245, 
        position: 'absolute',
        right: 0,
        top: 0,
    },
    mountainClimberTitle:{
        fontSize: 23,
        fontFamily: 'Rubik-Medium',
        color: 'black',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        top: 0,
        marginRight: 47,
        marginTop: 30,
    },
    mountainClimberDesc: {
        fontSize: 13,
        fontFamily: 'Rubik-Regular',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        marginTop: 105,
        marginLeft: 25,
        marginRight: 5
    },
    mountainClimberGif: {
        width: 170,
        height: 225,
        alignSelf: 'flex=start',
        marginLeft: 0,
        marginTop: 30,
    },
    sideShuffle: {
        width: 345,
        height: 215,
        justifyContent: 'center',
        alignSelf: 'center',
        marginTop: 65,
        marginBottom: 85
    },
    sideShuffleTextContent:{
        width: 190,
        height: 255, 
        position: 'absolute',
        right: 0,
        top: 0,
    },
    sideShuffleTitle:{
        fontSize: 23,
        fontFamily: 'Rubik-Medium',
        color: 'black',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        top: 0,
        marginRight: 47,
        marginTop: 30,
    },
    sideShuffleDesc: {
        fontSize: 13,
        fontFamily: 'Rubik-Regular',
        textAlign: 'left',
        position: 'absolute',
        right: 0,
        marginTop: 105,
        marginLeft: 25,
        marginRight: 5
    },
    sideShuffleGif: {
        width: 170,
        height: 225,
        alignSelf: 'flex=start',
        marginLeft: 0,
        marginTop: 30,
    },
})

export default styles;